### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.zh-tw#1]
English:
How should I use these files relative to the released MOC files?

Current Translation:
我該如何使用與相對於已釋放的 MOC 檔案之這些檔案？

Suggested Translation:
相對於發佈的 MOC 檔案，我應該如何使用這些檔案？

Description:
Mistranslation

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
The issue has been fixed, so I close the PR.
![image](https://user-images.githubusercontent.com/93902755/182305547-da6e3ef7-e10c-4ab8-8909-210535fe523d.png)
